# Generated by Django 4.0.7 on 2022-10-05 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(db_column='username', max_length=255, unique=True),
        ),
    ]
