# Generated by Django 4.0.7 on 2023-01-26 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_01', '0002_alter_users_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='rollback',
            field=models.BooleanField(null=True),
        ),
    ]
